#!/usr/bin/env bash
# Script to print the domain and subdomain information using DNS queries

print_domain_subdomain () {
    # Fetch DNS records and print subdomain, record type, and its destination
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " 'NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]; then
    # If two arguments are passed, use the second argument as subdomain
    print_domain_subdomain "$2.$1" "$2"
else
    # If only one argument is passed, print for default subdomains
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi
