#!/usr/bin/env bash

# Function to display usage
usage() {
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if number of arguments is less than 4, display usage and exit
if [ "$#" -lt 4 ]; then
  usage
  exit 1
fi

# Assigning parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Transfer the file using scp to the user's home directory (~)
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP":~

# Check if scp command was successful
if [ $? -eq 0 ]; then
  echo "File transferred successfully to $USERNAME@$IP:~/"
else
  echo "Failed to transfer file to $USERNAME@$IP"
fi
