#!/usr/bin/env bash
# Install nginx and move using 301

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/html/index.html

string_for_replacement="server_name _;\n\trewrite ^/redirect_me https://github.com/termication permanent;"

sudo sed -i "s|server_name _;|$string_for_replacement|" /etc/nginx/sites-enabled/default

sudo service nginx restart
