#!/usr/bin/env bash
# Installs and sets up HAProxy

# Update package list
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Append configuration to HAProxy configuration file
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOL

frontend Innocent
        bind *:80
        mode http
        default_backend app

backend app
        balance roundrobin
        server 459074-web-01 184.72.96.209:80 check
        server 459074-web-02 100.25.152.248:80 check
EOL

# Check if HAProxy configuration is valid
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
if [ $? -ne 0 ]; then
    echo "Error: HAProxy configuration is invalid."
    exit 1
fi

# Restart HAProxy to apply the new configuration
sudo systemctl restart haproxy

# Confirm HAProxy is running
sudo systemctl status haproxy
