#!/usr/bin/env bash
# this script enables sites to sites-avalaible and ngix to listen to port 80

apt-get update -y
apt-get install -y nginx
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
