#!/usr/bin/env bash
# This script sets up Nginx configuration by linking the default site configuration
# and starts the Nginx service without checking its status.

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start the Nginx service
sudo service nginx start

# Remove the Nginx PID file if it exists to avoid startup issues
rm /run/nginx.pid
