#!/usr/bin/env bash
# This script sets up Nginx configuration by linking the default site configuration and starts the Nginx service without checking its status.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
rm /run/nginx.pid
