#!/usr/bin/env bash
# Description: Display a list of currently running processes
# containing the word "bash".

# Disable shellcheck SC2009 warning for using grep in pipeline
shellcheck disable=SC2009

ps auxf | grep bash
