#!/usr/bin/env bash
# Script that  prints "bad luck" 4th line, "good luck" on the 8th line, and "Holberton School" for other iterations
n=1

while [ $n -le 20 ]
do
    echo $n
    case $n in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            ;;
    esac
    n=$(( n + 1 ))
done
