#!/usr/bin/env bash

# Define the server address
SERVER="34.229.161.59"

# Use SSH to connect to the server using the private key ~/.ssh/school with the user ubuntu
ssh -i ~/.ssh/school ubuntu@$SERVER
